### PR TITLE
add luciphor2.1

### PR DESCRIPTION
**Pull request by bernt-matthias**
- [x] This software or dataset's license allows us to distribute it. (Insert link to link to license here)
- [ ] This software or dataset is related to the biological sciences, galaxy, or similar areas.

ping @oliveralka

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Thanks. URL should be https://depot.galaxyproject.org/software/luciphor2.1/luciphor2.1_2020-04-03_all_all.jar ?

**Comment by bgruening** [comment]
https://depot.galaxyproject.org/software/luciphor2/luciphor2_2018-06-28_all_all.jar

**Comment by bernt-matthias** [comment]
This should be the link to the old one, or?

**Comment by bgruening** [comment]
So this is now fixed. Cargo-port was broken, its alive again.

**Comment by bgruening** [comment]
You link is correct and works now.

**Comment by bernt-matthias** [comment]
Thanks

**Pull request merged**
