### PR TITLE
added fold-grammars

### PR DESCRIPTION
**Pull request by HassanAmr**

### CODE REVIEW

**Comment by bgruening** [comment]
It needs to be tab separated.

**Comment by HassanAmr** [comment]
The `sha256sum` I get is  `47c04f7c03ca34b311a75b23b27339ce4629ae3ca13663ac2cfe6b65fa68b835`. Is it possible to restart the test in case something went wrong when downloading it.

**Comment by bgruening** [comment]
restarting does not help as it seems.

**Comment by erasche** [comment]
@HassanAmr please change the url to the following: https://raw.githubusercontent.com/bgruening/download_store/master/fold-grammar/fold-grammars.tar.gz

Accessing https://github.com/bgruening/download_store/blob/master/fold-grammar/fold-grammars.tar.gz just downloads the HTML page associated with it. By adding `?raw=true` to the end, and following the redirect, you'll get the raw.githubusercontent.com url.

**Comment by HassanAmr** [comment]
Thanks :)

**Pull request merged**
