### PR TITLE
Pysam 013

### PR DESCRIPTION
**Pull request by dannon**
- [x] This software or dataset is not more easily backed up by other systems (e.g. a conda package which could more easily be mirrored by a conda mirror)
- [x] This software or dataset's license allows us to distribute it. If possible please link to it.
- [x] This software or dataset is related to the sciences, galaxy, or similar areas.

### CODE REVIEW

**Comment by dannon** [comment]
@bgruening We never released or supported 0.12, though, so it shouldn't be here, right?

**Comment by bgruening** [comment]
@dannon this repo is a general backup of tarballs, also used by bioconda. So this version was just saved. removing these lines does not have any effect, but usually we don't remove lines.

**Comment by bgruening** [comment]
@dannon we need a rebase here I guess.

**Comment by dannon** [comment]
@bgruening Did it conflict?  I stripped out the last changeset I had added (adding the lines back) already.

**Comment by bgruening** [comment]
@erasche fixed a bug yesterday and I had hoped this will make this PR pass again.

**Comment by dannon** [comment]
@bgruening Got it!  Misunderstood the point of the rebase, done now.

**Pull request merged**
