### PR TITLE
added gem-library

### PR DESCRIPTION
**Pull request by lldelisle**
- [X] This software or dataset's license allows us to distribute it. (Insert link to link to license here)
- [X] This software or dataset is related to the biological sciences, galaxy, or similar areas.

Hi,
This is the first time I am using cargo-port...
1. For the url, I just click right on the sourgeforge webpage to get the url. When I do wget I see different URL:
```
[ldelisle@helvetios softwares]$ wget https://sourceforge.net/projects/gemlibrary/files/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2/download
--2020-02-10 11:30:02--  https://sourceforge.net/projects/gemlibrary/files/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2/download
Resolving scitassrv9.epfl.ch (scitassrv9.epfl.ch)... 128.178.209.216
Connecting to scitassrv9.epfl.ch (scitassrv9.epfl.ch)|128.178.209.216|:80... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://downloads.sourceforge.net/project/gemlibrary/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2?r=&ts=1581330603&use_mirror=liquidtelecom [following]
--2020-02-10 11:30:03--  https://downloads.sourceforge.net/project/gemlibrary/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2?r=&ts=1581330603&use_mirror=liquidtelecom
Connecting to scitassrv9.epfl.ch (scitassrv9.epfl.ch)|128.178.209.216|:80... connected.
Proxy request sent, awaiting response... 302 Found
Location: https://liquidtelecom.dl.sourceforge.net/project/gemlibrary/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2 [following]
--2020-02-10 11:30:04--  https://liquidtelecom.dl.sourceforge.net/project/gemlibrary/gem-library/Binary%20pre-release%203/GEM-binaries-Linux-x86_64-core_i3-20130406-045632.tbz2
Connecting to scitassrv9.epfl.ch (scitassrv9.epfl.ch)|128.178.209.216|:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: 33847526 (32M) [application/octet-stream]
Saving to: ‘download’

100%[=====================================================================================================================================================================================================================================>] 33,847,526  8.45MB/s   in 4.7s   

2020-02-10 11:30:10 (6.87 MB/s) - ‘download’ saved [33847526/33847526]

```
2. I am not sure I understood the last column of the file... I put false but maybe it should have been True (sourceforge did not ask to stop download, we are more afraid that the url is not stable)...
3. To get the license, I need to download and then run:
`GEM-binaries-Linux-x86_64-core_i3-20130406-045632/bin/gem-mappability --show-license`.
Here is the result:
```
Welcome to GEM-mappability build 1.315 (beta) - (2013/03/29 02:59:40 GMT)
 (c) 2008-2013 Paolo Ribeca <paolo.ribeca@gmail.com>
 (c) 2010-2013 Santiago Marco Sola <santiagomsola@gmail.com>
 (c) 2010-2013 Leonor Frias Moya <leonor.frias@gmail.com>
For the terms of use, run the program with the option --show-license.
************************************************************************
* WARNING: this is a beta version, provided for testing purposes only; *
*          check for updates at <http://gemlibrary.sourceforge.net>.   *
************************************************************************

This software is copyright
 (C) 2008-2010 Centre de Regulació Genòmica, Barcelona, Spain (CRG)
 (C) 2010-2012 Centro Nacional de Análisis Genómico, Barcelona, Spain (CNAG)
               Parc Científic de Barcelona, Spain (PCB)
and was developed by the following authors:
 (C) 2008-2012 Paolo Ribeca <paolo.ribeca@gmail.com> (CRG, CNAG)
 (C) 2010-2012 Santiago Marco Sola <santiagomsola@gmail.com> (CNAG)
 (C) 2010-2012 Leonor Frias Moya <leonor.frias@gmail.com> (CNAG)

=====================================
The GEM non-commercial binary license
=====================================

If you use the software, you accept this license. If you do not accept the license,
do not use the software.

The present license grants you the right to freely use for any purpose this binary
and all the results it generates, provided that the binary is not embedded in a
commercial software suite. That is: you may freely use the program either as a
standalone application or integrated into a larger non-commercial software
environment, but you may not use it (regardless of the way you obtained it) as a
component of a commercial system. If you realize that the software is being run in
violation of this rule, you must immediately stop using it and notify
<genome.multitool.legal@gmail.com> of the violation.

The present license also grants you the right to freely redistribute exact copies of
this binary for any non-commercial purpose. In particular: (1) you may not embed it
into, or allow it to be executed from, a commercial software suite (that is: you may
redistribute the program either as a standalone application or integrated into a
larger non-commercial software environment, but not as a component of a commercial
system) (2) you may not sell, rent, lease or lend the software (3) you may not
modify, reverse engineer, decompile or disassemble the software (4) you must retain
all copyright, patent, trademark, and attribution notices that are present in the
software, including this license (5) you may not misrepresent the origin of the
software, and the material you distribute must fairly acknowledge the presence of
the software with prominent notices.

Uses other than those explicitly allowed in this document require separate licensing
agreement from the copyright holders. In case of any doubt, please contact
<paolo.ribeca@gmail.com>.

THE PROGRAM IS PROVIDED "AS IS", WITHOUT ANY WARRANTY OF ANY KIND EITHER EXPRESSED
OR IMPLIED, IN THE HOPE THAT IT WILL BE USEFUL; THE ENTIRE RISK AS TO THE QUALITY
AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU
ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.
```

### CODE REVIEW

**Comment by bgruening** [comment]
> The present license also grants you the right to freely redistribute exact copies of
this binary for any non-commercial purpose.

I think this is fine for us. But please note that if you use this in a Galaxy wrapper, you probably need to ask the user if its for non-commercial use.

The False also looks like it, as Sourceforge is unstable in regards to URLs.

**Comment by bgruening** [comment]
Still want to merge it?

**Comment by lldelisle** [comment]
I guess I can I ask the owner for putting it in galaxy + bioconda, right?
Maybe we can wait its answer...

**Comment by bgruening** [comment]
> I guess I can I ask the owner for putting it in galaxy + bioconda, right?

Yes sure, but make sure that you make clear that a Galaxy admin can not know if a user is commercial or not. Its a public server that we need to assume.

**Comment by lldelisle** [comment]
Yes, I will do like for the MEME suite in tools-iuc (check box + warning in the help).
Thank you very much for pointing this.

**Comment by lldelisle** [comment]
Apparently, the owner is going to make available a new version on a "stable" url...
Thanks

**Pull request closed without merging**
