### PR TITLE
Add fastqc version 0.11.4

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by erasche** [comment]
LGTM, thanks @gregvonkuster!

**Comment by gregvonkuster** [comment]
Thanks for the merge @erasche .  Any idea when these will be available here?  https://depot.galaxyproject.org/software/

**Comment by bgruening** [comment]
Around one hour later :)

**Comment by erasche** [comment]
@gregvonkuster, it should be there. Search on 'fastqc' https://depot.galaxyproject.org/software/

Jenkins said it was successful: https://jenkins.galaxyproject.org/view/Meta/job/cargo-port/144/

**Comment by gregvonkuster** [comment]
Ok, just showed up.  Thanks!!  ;)

**Pull request merged**
