### PR TITLE
Sort urls.tsv and fix associated issues

### PR DESCRIPTION
**Pull request by peterjc**
This is a cut down version of pull request #89 focusing on the sorting issues only, see #88

### CODE REVIEW

**Comment by peterjc** [comment]
TravisCI validation fails as you can't use curl to download the legacy filenames like ``/srv/nginx/depot.galaxyproject.org/root/package/linux/x86_64/samtools/samtools-1.2+gx1-Linux-x86_64.tar.gz`` which are listed in ``urls.tsv`` as the Upstream URL.

We could:
 - Ignore the failure and merge anyway
 - Whitelist these in the CI validation
 - Replace the ``/svr/...`` links with working legacy URLs like http://depot.galaxyproject.org/package/linux/x86_64/samtools/samtools-1.2+gx1-Linux-x86_64.tar.gz with a simple search-and-replace
 - Best of all, replace the ``/srv/...`` links with the original URLs (if that information readily available)?

**Comment by erasche** [comment]
> Replace the /srv/... links with working legacy URLs like

is probably the easiest option, pending someone digging up original URLs for everything. These may not in fact exist, since some of the tarballs are compiled artefacts and may include non-reproducible build contents.

Here's a sed, so I feel less bad asking if you wouldn't mind making the change as part of your PR?

```console
sed -i "s|/srv/nginx/depot.galaxyproject.org/root/|http://depot.galaxyproject.org/|g" urls.tsv
```

**Comment by peterjc** [comment]
Change applied as new commit with sed - I agree this is the best option in the short term.

**Comment by erasche** [comment]
This looks great, thank you very much @peterjc. For anyone else's benefit who is reading this: I'm merging this now because

- the changes are sorting + replacing of depot URLs with real URLs.
- these changes won't affect existing artefacts on the server
- it will fail due to other bad hashes from upstreams

**Comment by peterjc** [comment]
Great 👍

**Pull request merged**
