### PR TITLE
add luciphor

### PR DESCRIPTION
**Pull request by bernt-matthias**
in order to have a stable versioned link

- [ ] This software or dataset's license allows us to distribute it. (Insert link to link to license here)
- [x] This software or dataset is related to the biological sciences, galaxy, or similar areas.

Has apache2 license according to http://luciphor2.sourceforge.net/ .. is this fine?

### CODE REVIEW

**Comment by bgruening** [comment]
Super fine.

**Comment by bernt-matthias** [comment]
Always forget how the download link will look. Can you help me out @bgruening ?

**Comment by bgruening** [comment]
@bernt-matthias it seems to be broken atm.

@natefoo can you look at this. https://jenkins.galaxyproject.org/view/Meta/job/cargo-port/

**Comment by bernt-matthias** [comment]
Does someone know if this is available now and tell me the download link?

**Comment by natefoo** [comment]
@bgruening Was that a 404 when you wrote that comment or was I too slow and Jenkins has cleaned it up?

**Comment by bernt-matthias** [comment]
Just had the wrong link I suppose. Finally I got the correct one with the tool that I fixed here: https://github.com/galaxyproject/cargo-port/pull/166

**Comment by bgruening** [comment]
Thanks for checking @natefoo!

**Pull request merged**
