### PR TITLE
adding conda deb package

### PR DESCRIPTION
**Pull request by bgruening**
@erasche is this ok for you?

### CODE REVIEW

**Comment by erasche** [comment]
yep! that's fine. Then easier than using a mirrored repo, no need to mess with apt lists, just `wget / dpkg`, easy. Good plan.

**Comment by bgruening** [comment]
Mh, it does not seem to have worked. I guess the .dev is a problem as type?

**Comment by erasche** [comment]
ahh sigh ok

**Comment by erasche** [comment]
- we just had to get lucky, same issue you had.
- `.deb` shouldn't be a problem
- changed id to `condor`, since you clearly are thinking about conda too much ;)

**Pull request merged**
