### PR TITLE
added qualimap downlodable link

### PR DESCRIPTION
**Pull request by zipho**

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks! :)

**Comment by zipho** [comment]
Thank you also.

Will the change suffice to have the QualiMap package link added to be visible/accessible at https://depot.galaxyproject.org/software or will I need to do something extra?

When can I expect it to be available? :-)
 
Kind Regards

**Comment by bgruening** [comment]
Everything is now set. Expect the package on depot not later than an hour from now.

**Comment by zipho** [comment]
Thanks so much..

**Pull request merged**
