### PR TITLE
cfm: add cfm sources to cargo port

### PR DESCRIPTION
**Pull request by bernt-matthias**
- the sourceforge link deprecates after 1d
- needed here https://github.com/bernt-matthias/bioconda-recipes/tree/topic/cfmid-progress/recipes/cfm-id/

- [x] This software or dataset's license allows us to distribute it. (https://sourceforge.net/p/cfm-id/code/HEAD/tree/cfm/license.txt)
- [x] This software or dataset is related to the biological sciences, galaxy, or similar areas.

### CODE REVIEW

**Comment by bgruening** [comment]
Merci!

**Comment by bernt-matthias** [comment]
Hey @bgruening. I guess the source forge link expired or it didn't start yet. I activated the download ling at source forge again. Could you trigger the download again? Thanks

**Comment by bernt-matthias** [comment]
Maybe I was wrong. @RJMW already sent me a working link: https://depot.galaxyproject.org/software/cfm/cfm_r33_src_all.tar.gz but it should be zip. I guess I have chose a wrong entry in the corresponding column. Should I open a new PR? I guess this will confuse bioconda.

**Comment by bgruening** [comment]
@bernt-matthias can you check this in a few minutes. I tried to fix it.

**Comment by bernt-matthias** [comment]
the check for https://depot.galaxyproject.org/software/cfm/cfm_r33_src_all.zip was negative. the old link still works.

**Comment by bgruening** [comment]
@bernt-matthias check again please.

**Pull request merged**
