### PR TITLE
add maxquant 2.4.2.0

### PR DESCRIPTION
**Pull request by bernt-matthias**
- [x] This software or dataset's license allows us to distribute it. (Insert link to link to license here)
  http://www.coxdocs.org/lib/exe/fetch.php?media=license_agreement.pdf
- [x] This software or dataset is related to the biological sciences, galaxy, or similar areas.

I double checked that the checksums of the download from the official site and the google drive match.

### CODE REVIEW

**Comment by bgruening** [comment]
Let's see if this still works :-)

**Comment by bernt-matthias** [comment]
At least something ran, but errored: 

```
rsync -avr --exclude bioconda-recipes --exclude .git . depot@orval.galaxyproject.org:/srv/nginx/depot.galaxyproject.org/root/software/
ssh: connect to host orval.galaxyproject.org port 22: No route to host
```

**Comment by bernt-matthias** [comment]
https://jenkins.galaxyproject.org/job/cargo-port/2857/console

**Comment by bgruening** [comment]
Mh, too bad we need @natefoo here

**Comment by natefoo** [comment]
It's `rochefort.galaxyproject.org` now.

**Comment by bernt-matthias** [comment]
How can we rerun CI here? Just open 2 PRs (remove and readd)?

**Pull request merged**
