### PR TITLE
User help for using packages

### PR DESCRIPTION
**Pull request by erasche**
selection_518

Using string templates from ES6 because I really don't care about old browsers.

### CODE REVIEW

**Comment by erasche** [comment]
cc @bgruening @martenson anything else I should add to this form?

**Comment by martenson** [comment]
`to clipboard` button?

**Comment by erasche** [comment]
yea, ok, can add.

**Comment by martenson** [comment]
awesome-O

**Comment by bgruening** [comment]
Damn it you beat me on that ... have something similar and uglier in a cleanup branch :)
Great!
I would indicate that it is a Galaxy package. We should not forget that this project should also be used by non-Galaxy devs.
Any idea how we can get the different package types? Like the ones for R or Python packages? My patch has just a list of URL and checksum, no clue how we can offer all at once.

**Comment by erasche** [comment]
>I would indicate that it is a Galaxy package. We should not forget that this project should also be used by non-Galaxy devs.

Good point! I'll make it more generic

> Any idea how we can get the different package types? Like the ones for R or Python packages? My patch has just a list of URL and checksum, no clue how we can offer all at once.

Hmmm. A good thought. That would be nice. I'm not sure we can capture/expose all of that without significant pain. I'll think about it over the weekend.

**Pull request merged**
