### PR TITLE
Add URL for meme 4.11.0

### PR DESCRIPTION
**Pull request by gregvonkuster**
@bgruening This should include the additional column.

### CODE REVIEW

**Comment by erasche** [comment]
Thanks @gregvonkuster, looks good!

**Comment by erasche** [comment]
This was downloaded, but had a bad hash relative to the one you supplied. Can you please confirm the sha256sum of `meme_4.11.0.tar.gz`?

**Comment by gregvonkuster** [comment]
@erasche What do you use to generate them?  I've been using free online stuff, maybe not a good idea?

**Comment by erasche** [comment]
@gregvonkuster I use sha256sum on the CLI, but I live in the terminal, so maybe not the best for everyone. I get a value of `5dc4841f4816ef25bdb4bd088c76606c1b42726e7d65cc417f0f8c49fe7e237f` for the URL http://meme-suite.org/meme-software/4.11.0/meme_4.11.0.tar.gz

**Comment by gregvonkuster** [comment]
@erasche Hmmm I don't get that, but I'll just copy and paste it.  Thanks!

**Comment by gregvonkuster** [comment]
@erasche Fixed here: https://github.com/galaxyproject/cargo-port/pull/40  Thanks!

**Pull request merged**
